SmartBase/Entities/Stored/Device.cs
using System;

namespace SmartBase.Entities.Stored
{
    public class Device
    {
        public Guid Id { get; set; }

        public Endpoint Endpoint { get; set; }
        
        public string Ip { get; set; }
    }
}

SmartBase/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartBase.Entities;
using SmartBase.Entities.Capabilities;
using SmartBase.Entities.Stored;
using SmartBase.Models;
using SmartBase.Repositories;
namespace SmartBase.Controllers
{
    public class DeviceController : Controller
    {
        readonly DeviceRepo _deviceRepo;

        public DeviceController(DeviceRepo deviceRepo)
        {
            _deviceRepo = deviceRepo;
        }

        public IActionResult List()
        {
            return View(new DevicesModel
            {
                Devices = _deviceRepo.FindAll()
            });
        }

        public IActionResult Add()
        {
            var data = new AddDeviceModel
            {
                CapabilityData = new SelectList(new List<SelectListItem>
                {
                    new SelectListItem {Text = "PowerController", Value = "PowerController"},
                    new SelectListItem {Text = "ColorController", Value = "ColorController"},
                    new SelectListItem {Text = "BrightnessController", Value = "BrightnessController"},
                    new SelectListItem {Text = "PowerLevelController ", Value = "PowerLevelController "},
                    new SelectListItem {Text = "PercentageController ", Value = "PercentageController "},
                    new SelectListItem {Text = "TemperatureSensor", Value = "TemperatureSensor"}
                }, "Value", "Text")
            };

            return View(data);
        }

        [HttpPost]
        public IActionResult Save(AddDeviceModel data)
        {
            var id = Guid.NewGuid();
            if (data.Id.HasValue)
            {
                id = data.Id.Value;
            }
            
            var device = new Device { Endpoint = data.Endpoint, Ip = data.Ip, Id = id};
            device.Endpoint.EndpointId = id;

            var capabilities = new List<Capability>();
            foreach (var capability in data.Capabilities)
            {
                if(capability.Equals("PowerController"))
                    capabilities.Add(new PowerController());
                if (capability.Equals("ColorController"))
                    capabilities.Add(new ColorController());
                if (capability.Equals("BrightnessController"))
                    capabilities.Add(new BrightnessController());
                if (capability.Equals("PercentageController "))
                    capabilities.Add(new PercentageController());
                if (capability.Equals("PowerLevelController "))
                    capabilities.Add(new PowerLevelController());
                if (capability.Equals("TemperatureSensor"))
                    capabilities.Add(new TemperatureSensor());
            }
            device.Endpoint.Capabilities = capabilities;

            if (data.Id.HasValue)
            {
                _deviceRepo.Update(device);
            }
            else
            {
                _deviceRepo.Add(device);
            }
            
            return RedirectToAction("List");
        }

        public IActionResult Edit(Guid id)
        {
            var device = _deviceRepo.FindById(id);

            var data = new AddDeviceModel
            {
                Id = device.Id,
                Ip = device.Ip,
                Endpoint = device.Endpoint,
                CapabilityData = new SelectList(new List<SelectListItem>
                {
                    new SelectListItem {Text = "PowerController", Value = "PowerController"},
                    new SelectListItem {Text = "ColorController", Value = "ColorController"},
                    new SelectListItem {Text = "BrightnessController", Value = "BrightnessController"},
                    new SelectListItem {Text = "PowerLevelController ", Value = "PowerLevelController "},
                    new SelectListItem {Text = "PercentageController ", Value = "PercentageController "},
                    new SelectListItem {Text = "TemperatureSensor", Value = "TemperatureSensor"}
                }, "Value", "Text")
            };

            foreach (var capability in data.CapabilityData)
            {
                foreach (var endpointCapability in device.Endpoint.Capabilities)
                {
                    if (capability.Text.Equals(endpointCapability.Interface.Substring(endpointCapability.Interface.LastIndexOf('.') + 1)))
                    {
                        capability.Selected = true;
                    }
                }
            }

            return View("Add", data);
        }

        public IActionResult Delete(Guid id)
        {
            _deviceRepo.DeleteById(id);
            return RedirectToAction("List");
        }
    }
}

SmartBase/Views/Device/Add.cshtml
@model AddDeviceModel
@{
    ViewData["Title"] = "Add Device";
}
<h2>@ViewData["Title"]</h2>
@using (Html.BeginForm("Save", "Device", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <table>
        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.FriendlyName)</td>
            <td>@Html.EditorFor(model => model.Endpoint.FriendlyName)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.Description)</td>
            <td>@Html.EditorFor(model => model.Endpoint.Description)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.Cookie.ExtraDetail1)</td>
            <td>@Html.EditorFor(model => model.Endpoint.Cookie.ExtraDetail1)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.Cookie.ExtraDetail2)</td>
            <td>@Html.EditorFor(model => model.Endpoint.Cookie.ExtraDetail2)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.Cookie.ExtraDetail3)</td>
            <td>@Html.EditorFor(model => model.Endpoint.Cookie.ExtraDetail3)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.Cookie.ExtraDetail4)</td>
            <td>@Html.EditorFor(model => model.Endpoint.Cookie.ExtraDetail4)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.ManufacturerName)</td>
            <td>@Html.EditorFor(model => model.Endpoint.ManufacturerName)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.DisplayCategories)</td>
            <td>@Html.DropDownListFor(model => model.Endpoint.DisplayCategories, Model.DisplayCategoryData)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.Endpoint.Capabilities)</td>
            <td>@Html.ListBoxFor(model => model.Capabilities, Model.CapabilityData)</td>
        </tr>

        <tr>
            <td> @Html.LabelFor(model => model.Ip)</td>
            <td> @Html.EditorFor(model => model.Ip)</td>
        </tr>
    </table>

    @Html.HiddenFor(model => model.Id)

    <input type="submit" value="Save" class="btn btn-default" />
}

SmartBase/Views/Device/List.cshtml
@model DevicesModel
@{
    ViewData["Title"] = "Devices";
}
<h2>@ViewData["Title"]</h2>


<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Beschreibung</th>
        <th>Details</th>
        <th>Hersteller</th>
        <th>Kategorie</th>
        <th>Funktionen</th>
        <th>Ip</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var d in Model.Devices)
    {
    <tr>
        <td>@d.Endpoint.EndpointId</td>
        <td>@d.Endpoint.FriendlyName</td>
        <td>@d.Endpoint.Description</td>
        <td>
            <table>
                <tr><td>@d.Endpoint.Cookie.ExtraDetail1</td></tr>
                <tr><td>@d.Endpoint.Cookie.ExtraDetail2</td></tr>
                <tr><td>@d.Endpoint.Cookie.ExtraDetail3</td></tr>
                <tr><td>@d.Endpoint.Cookie.ExtraDetail4</td></tr>
            </table>
        </td>
        <td>@d.Endpoint.ManufacturerName</td>
        <td>
            @if (d.Endpoint.DisplayCategories != null)
        {
            foreach (var dis in d.Endpoint.DisplayCategories)
            {
                if (d.Endpoint.DisplayCategories.IndexOf(dis) != d.Endpoint.DisplayCategories.Count - 1)
                {
                    @String.Concat(dis.ToString(), ",")<br>
            }
            else
            {
                @dis.ToString()
        }
    }
}
        </td>
        <td>
            @if (d.Endpoint.Capabilities != null)
        {
            foreach (var cap in d.Endpoint.Capabilities)
            {
                if (d.Endpoint.Capabilities.IndexOf(cap) != d.Endpoint.Capabilities.Count - 1)
                {
                    @String.Concat(cap.Interface, ",")<br>
            }
            else
            {
                @cap.ToString()
        }
    }
}
        </td>
        <td>@d.Ip</td>
        <td>@Html.ActionLink("Edit", "Edit", "Device", new { id = d.Id }, null)</td>
        <td>@Html.ActionLink("Delete", "Delete", "Device", new { id = d.Id }, null)</td>
    </tr>
    }
</table>